AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless app infrastructure'

Resources:
  HostingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-hosting-bucket'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  DataTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AWS::StackName}-data-table'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  APIFunction:
    Type: 'AWS::Lambda::Function'
    FunctionUrlConfig:
        AuthType: NONE
    Properties:
      FunctionName: !Sub '${AWS::StackName}-function'
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: /apps/backend/dist/index.js
      Environment:
        Variables:
          TABLE_NAME: !Ref DataTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable

Outputs:
  HostingBucketName:
    Description: 'Name of the S3 bucket for hosting'
    Value: !Ref HostingBucket
    Export:
      Name: !Sub '${AWS::StackName}-HostingBucket'

  DataTableName:
    Description: 'Name of the DynamoDB table'
    Value: !Ref DataTable
    Export:
      Name: !Sub '${AWS::StackName}-DataTable'